### ISSUE TITLE
Nuget.config references private repository

### ISSUE THREAD

**Issue by amaitland** [JetBrains/Refasmer#1]
Attempting to build commit https://github.com/JetBrains/Refasmer/commit/879aae5c01b57a9ff501daf7b0c82332b6157e75 with `VS2019 16.7.0`.

When attempting to restore the Nuget packages I'm encountering the following error

```
Error occurred while restoring NuGet packages: Failed to retrieve information about 'Microsoft.Extensions.DependencyInjection' from remote source 'http://dotnet-build-nuget.labs.intellij.net/api/v2/FindPackagesById()?id='Microsoft.Extensions.DependencyInjection'&semVerLevel=2.0.0'.				
```

It appears the [Nuget.config](https://github.com/JetBrains/Refasmer/blob/master/NuGet.Config) file in the project root contains entries for private nuget repositories.

If I close `Visual Studio` then delete `Nuget.config` then I'm able to build the project successfully.

**Comment by zabbius** [comment]
Fixed, thank you.

**Comment by amaitland** [comment]
Great, thank you.
