### ISSUE TITLE
.NET6

### ISSUE THREAD

**Issue by krafs** [JetBrains/Refasmer#12]
Any plans to target .NET6?

**Comment by zabbius** [comment]
https://github.com/JetBrains/Refasmer/pull/13

**Comment by jnm2** [comment]
You need `<RollForward>Major</RollForward>` in the csproj for the compiled app to be able to run on newer major versions.

https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#rollforward

**Comment by ForNeVeR** [comment]
@jnm2, thanks for your suggestion. I'll apply it.
