### ISSUE TITLE
Conversion fails because of "Sequence contains more than one matching element"

### ISSUE THREAD

**Issue by bplu4t2f** [JetBrains/Refasmer#14]
Been using the latest version as of today to create reference assemblies from some third party DLLs.

It fails to convert NationalInstruments.Visa.dll, which is part of NI VISA, which can be downloaded from NI's website. I have attached the file for convenience.

The file looks ordinary enough to me in ILSpy.

Full console output:
```
D:\Refasmer.net461.1.0.30>refasmerexe -v "D:\tmp\NationalInstruments.Visa.dll"
 Processing 1 assemblies
 Processing D:\tmp\NationalInstruments.Visa.dll
  [NationalInstruments.Visa.dll] Using AllowPublic entity filter
  [NationalInstruments.Visa.dll] Sequence contains more than one matching element
```

[NationalInstruments.Visa.dll.zip](https://github.com/JetBrains/Refasmer/files/9886963/NationalInstruments.Visa.dll.zip)

**Comment by zabbius** [comment]
Problem appears because dll has references to two different mscrolib dlls. Investigating...

**Comment by zabbius** [comment]
@ForNeVeR FYI https://github.com/JetBrains/Refasmer/pull/16
