### ISSUE TITLE
Nuget Package/Binary Release 

### ISSUE THREAD

**Issue by amaitland** [JetBrains/Refasmer#2]
Is there a plan to package a release in any form?

- [.Net Core Tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) 
- Binary (zip) release here on GitHub 
- A more traditional Nuget package (tools folder with some callable targets)

I'd like to integrate Refasmer into my build process and even a zip I can download and extract from GitHub would greatly simplify the process. 

If there's no plan to release a binary build then a note in the Readme.md would be nice.

**Comment by zabbius** [comment]
I think we can release Refasmer in some way. Now we are thinking which way is the best.

**Comment by mfilippov** [comment]
Refasmer released:
- as NuGet lib (https://www.nuget.org/packages/JetBrains.Refasmer/1.0.12)
- as .NET Global tool (https://www.nuget.org/packages/JetBrains.Refasmer.CliTool/1.0.12)
