### ISSUE TITLE
Wildcard support doesn't work

### ISSUE THREAD

**Issue by craigktreasure** [JetBrains/Refasmer#3]
I was trying out your sample command (`RefasmerExe.exe -v -O ref -c *.dll`) using a wildcard (*), but wildcards don't appear to be supported. It treats it as a literal path and throws a System.IO.IOException indicating that the path couldn't be found.

Also, the executable is not `RefasmerExe.exe`. It is simply `refasmer`.

Very cool project! Thanks!

**Comment by mfilippov** [comment]
@craigktreasure Thank you for the feedback. We updated documentation.
