### ISSUE TITLE
Official Microsoft.NETFramework.ReferenceAssemblies.net35 is now on nuget.org

### ISSUE THREAD

**Issue by jnm2** [JetBrains/Refasmer#5]
Just a heads up, you may want to consider marking https://www.nuget.org/packages/JetBrains.NETFramework.ReferenceAssemblies.net35 obsolete like I'm doing with jnm2.ReferenceAssemblies.net35:

![image](https://user-images.githubusercontent.com/8040367/117220437-355f2800-add5-11eb-8d28-42bdbdd96327.png)

The official package fixes the filename casing issue.

**Comment by jnm2** [comment]
Sorry, not sure why I closed the issue. Want to make sure you see this.

**Comment by zabbius** [comment]
@mfilippov FYI

**Comment by mfilippov** [comment]
@jnm2 Thank you for the feedback. Package deprecated.
