### ISSUE TITLE
AnyCPU architecture

### ISSUE THREAD

**Issue by miloush** [JetBrains/Refasmer#7]
It looks like the generated referenced assemblies retain the same architecture of the original assembly targets. However, one of the reasons to create a reference assembly is to create a platform independent assembly that can be used regardless of the target platform (e.g. as NuGet's ref).

I am not quite sure why a platform specific reference assembly would be needed, but there should at least be an option for the reference assembly to target AnyCPU architecture.

I noticed that the `ManagedPEBuilder` is constructed with the default `CorFlags`, so it turns x86 assemblies into Any CPU (64-bit preferred) anyway.

**Comment by zabbius** [comment]
Do you mean `peReader.PEHeaders.CoffHeader.Machine` field or something else?

**Comment by miloush** [comment]
Correct. You copy the `Machine` over from the source assembly to the newly created one, but you don't copy the `CorFlags`. That changes the target CPU of the assembly.

In order to produce Any CPU reference assembly, I am suggesting to change

https://github.com/JetBrains/Refasmer/blob/00b02f4707723344016360acea9ff7799eaaa1da/src/Refasmer/Importer/MetadataImporter.cs#L55

to `Machine.I386`. If a command line parameter was preferred, however, a way to pass options into the metadata importer would need to be designed.

**Comment by zabbius** [comment]
Not sure that we need commandline setting for this. Fixed in 1.0.18.
