### ISSUE TITLE
System.TypeLoadException: Abstract method with non-zero RVA.

### ISSUE THREAD

**Issue by A-Ovchinnikov-mx** [JetBrains/Refasmer#9]
Hi,

I'm hitting this error when trying to load information about types in a mock assembly generated by Refasmer.

I suppose this might have something to do with the fact that Refasmer generates method body for interface methods.

Here's a sample project:

[RefasmerIssue.zip](https://github.com/JetBrains/Refasmer/files/7488090/RefasmerIssue.zip)

Try replacing the `InterfaceLib.dll` with a mock (`refasmer -m -w InterfaceLib.dll`) and it will crash 🙂

Could you please take a look into this issue?

Thanks!

**Comment by zabbius** [comment]
@A-Ovchinnikov-mx please try 1.0.20. I've fixed non-empty interface methods and special `<Module>` type.

**Comment by zabbius** [comment]
Fixed this bug and some additional.
